vim.keymap.set("n", "<leader>bp", function ()
    vim.cmd.vnew()
    vim.cmd.term()
    vim.cmd.wincmd("J")
    vim.api.nvim_win_set_height(0, 10)
    local job_id = vim.bo.channel
    vim.fn.chansend(job_id, { "make build\r\n" })
end)
vim.keymap.set("n", "<leader>rp", function ()
    vim.cmd.vnew()
    vim.cmd.term()
    vim.cmd.wincmd("J")
    vim.api.nvim_win_set_height(0, 10)
    local job_id = vim.bo.channel
    vim.fn.chansend(job_id, { "make run\r\n" })
end)
